const API='http://127.0.0.1:8000/api';const assets=[{key:'gold',label:'Gold',color:'#7f8cff'},{key:'bitcoin',label:'Bitcoin',color:'#ff5a3d'},{key:'nvidia',label:'NVIDIA',color:'#00d5a0'}];const views={overview:['◈','Overview','Market overview'],explorer:['▣','Asset Explorer','Technical intelligence'],correlation:['◫','Correlation Lab','Cross-asset dependency map'],strategy:['⚡','Strategy Lab','Alpha engine selection'],backtest:['◉','Backtest Lab','Portfolio simulation and performance'],regimes:['△','Market Regimes','Macro climate decomposition'],adaptive:['◎','Adaptive Lab','Regime-aware allocation'],stress:['◇','Stress Lab','Edge-case resilience testing'],summary:['✦','Research Summary','Executive decision brief']};const charts={};const $=id=>document.getElementById(id);if(typeof Chart!=='undefined'){Chart.defaults.color='#8d95a5';Chart.defaults.font.family='IBM Plex Sans, Segoe UI, sans-serif'}

function nav(){const html=Object.entries(views).map(([key,v])=>`<button class="nav-button" data-view-button="${key}"><b>${v[0]}</b>${v[1]}</button>`).join('');$('desktopNav').innerHTML=html;$('mobileNav').innerHTML=html;document.querySelectorAll('[data-view-button]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.viewButton)));}
function showView(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.dataset.view===name));document.querySelectorAll('[data-view-button]').forEach(button=>button.classList.toggle('active',button.dataset.viewButton===name));$('sectionEyebrow').textContent=views[name][1];$('pageTitle').textContent=views[name][2];}
async function get(path){const response=await fetch(API+path);if(!response.ok)throw new Error(path);return response.json()}
function metric(label,value,sub=''){return `<article class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div>${sub?`<div class="metric-sub">${sub}</div>`:''}</article>`}
function pct(value,digits=2){return `${(Number(value||0)*100).toFixed(digits)}%`}function money(value){return `$${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:2})}`}
function normalize(series){const first=Number(series[0]?.close)||1;return series.map(row=>Number(row.close)/first*100)}
function destroy(name){if(charts[name])charts[name].destroy()}
function lineChart(name,id,labels,datasets,options={}){destroy(name);charts[name]=new Chart($(id),{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},animation:{duration:350},plugins:{legend:{labels:{color:'#cbd2de'}},tooltip:{backgroundColor:'#171b23',borderColor:'#343b49',borderWidth:1}},scales:{x:{grid:{color:'rgba(122,133,151,.12)'},ticks:{maxTicksLimit:8,maxRotation:0,color:'#8d95a5'}},y:{grid:{color:'rgba(122,133,151,.16)'},ticks:{color:'#8d95a5'}}},...options}})}
async function loadOverview(){
	const data=await get('/assets');
	const cards=data.assets||[];
	$('overviewCards').innerHTML=cards.map(item=>metric(item.label,money(item.summary.price),`Daily ${pct(item.summary.daily_change)} | Sharpe ${Number(item.summary.sharpe||0).toFixed(2)}`)).join('');
	const period=$('overviewPeriod').value;
	const payloads=await Promise.all(assets.map(asset=>get(`/assets/${asset.key}?period=${period}`)));
	const labels=payloads[0].series.map(row=>row.date);
	const datasets=payloads.map((payload,i)=>({label:assets[i].label,data:normalize(payload.series),borderColor:assets[i].color,pointRadius:0,borderWidth:2,tension:.12}));
	lineChart('performance','performanceChart',labels,datasets);
	$('sourceStatus').textContent=payloads.every(p=>p.live)?'Live sync online':'Fallback data online';
	$('lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString()}`;
}
async function loadExplorer(){const data=await get(`/assets/${$('assetSelect').value}?period=${$('assetPeriod').value}`);const s=data.series||[];const sum=data.summary||{};$('assetMetrics').innerHTML=[metric('Price',money(sum.price)),metric('Daily',pct(sum.daily_change)),metric('Sharpe',Number(sum.sharpe||0).toFixed(2)),metric('Max drawdown',pct(sum.max_drawdown))].join('');const last=s[s.length-1]||{};const signals=[['50 EMA',last.close>last.ema50?'Bullish':'Below average',last.close>last.ema50?78:35],['200 EMA',last.close>last.ema200?'Trend support':'Trend risk',last.close>last.ema200?72:30],['Volatility',`${pct(last.volatility)} annualized`,Math.min(95,Number(last.volatility||0)*140)],['Drawdown',pct(last.drawdown),Math.max(8,100+Number(last.drawdown||0)*180)]];$('signals').innerHTML=signals.map(x=>`<div class="signal"><div class="signal-top"><span>${x[0]}</span><span>${x[1]}</span></div><div class="signal-bar"><i style="width:${x[2]}%"></i></div></div>`).join('');lineChart('asset','assetChart',s.map(x=>x.date),[['Close','close','#e8ebf0'],['SMA50','sma50','#f5c451'],['EMA50','ema50','#7f8cff'],['EMA200','ema200','#00d5a0']].map(x=>({label:x[0],data:s.map(row=>row[x[1]]),borderColor:x[2],pointRadius:0,borderWidth:x[0]==='Close'?2:1.4,tension:.18})))}
async function loadCorrelation(){const data=await get('/correlation');$('correlationSource').textContent=data.source||'';const labels=data.labels||[];const matrix=data.matrix||[];$('correlationMatrix').innerHTML=`<table class="matrix"><thead><tr><th>Asset</th>${labels.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${matrix.map((row,i)=>`<tr><th>${labels[i]}</th>${row.map(value=>{const v=Number(value);const color=v>=0?'127,140,255':'255,90,61';return `<td style="background:rgba(${color},${Math.min(.8,Math.max(.12,Math.abs(v)))});">${v.toFixed(2)}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function setMetrics(id,items){$(id).innerHTML=items.map(x=>metric(x[0],x[1],x[2]||'')).join('')}
async function runBacktest(asset=$('backtestAsset').value){const body={asset,initial_capital:Number($('capital').value)||10000,position_size:Number($('position').value)||1,transaction_cost:Number($('cost').value)||0};const response=await fetch(API+'/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();const m=data.metrics||{};setMetrics('backtestMetrics',[['Total return',pct(m.total_return)],['Sharpe',Number(m.sharpe||0).toFixed(2)],['Max drawdown',pct(m.max_drawdown)],['Final value',money(m.final_value)]]);lineChart('backtest','backtestChart',(data.curve||[]).map(x=>x.date),[{label:'Strategy',data:(data.curve||[]).map(x=>x.strategy),borderColor:'#00d5a0',pointRadius:0,borderWidth:2,tension:.2},{label:'Buy & Hold',data:(data.curve||[]).map(x=>x.benchmark),borderColor:'#f5c451',pointRadius:0,borderWidth:1.5,tension:.2}]) ;return m}
async function loadStrategy(){const m=await runBacktest($('strategyAsset').value);const score=Math.max(0,Math.min(100,50+Number(m.sharpe||0)*22));setMetrics('strategyMetrics',[['Annual return',pct(m.total_return)],['Win rate',`${Math.round(Math.max(35,Math.min(82,50+Number(m.sharpe||0)*16)))}%`],['Avg R:R',`${Math.max(.8,1.1+Number(m.sharpe||0)*.8).toFixed(1)}x`]]);destroy('strategy');charts.strategy=new Chart($('strategyChart'),{type:'radar',data:{labels:['Trend','Momentum','Sharpe','Risk','Consistency','Diversification'],datasets:[{label:'Strategy profile',data:[score,score*.9,score,Math.max(20,100+Number(m.max_drawdown||0)*200),score*.85,68],borderColor:'#7f8cff',backgroundColor:'rgba(127,140,255,.18)',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#cbd2de'}}},scales:{r:{min:0,max:100,grid:{color:'rgba(148,163,184,.2)'},angleLines:{color:'rgba(148,163,184,.2)'},pointLabels:{color:'#e8ebf0'},ticks:{display:false}}}}})}
async function loadRegimes(){const data=await get(`/regimes/${$('assetSelect').value}`);const rows=data.regimes||[];$('regimeCards').innerHTML=rows.map(x=>metric(x.regime,`${x.days} days`,`${pct(x.return)} return | ${pct(x.volatility)} vol`)).join('');destroy('regime');charts.regime=new Chart($('regimeChart'),{type:'bar',data:{labels:rows.map(x=>x.regime),datasets:[{label:'Regime return',data:rows.map(x=>Number(x.return)*100),backgroundColor:rows.map(x=>x.color)}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:'rgba(148,163,184,.14)'},ticks:{callback:v=>`${v}%`}}}}})}
function loadStatic(){setMetrics('adaptiveCards',[['Adaptive score','81.4','Risk-adjusted allocation score'],['Suggested allocation','42 / 33 / 25','BTC / Gold / NVIDIA'],['Regime adjustment','Bullish tilt','Trend exposure maintained']]);destroy('adaptive');charts.adaptive=new Chart($('adaptiveChart'),{type:'bar',data:{labels:['Gold','Bitcoin','NVIDIA'],datasets:[{label:'Suggested weight',data:[33,42,25],backgroundColor:['#f5c451','#ff5a3d','#00d5a0']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});$('stressCards').innerHTML=[['Liquidity shock','Fast volatility spike with elevated drawdown risk.','Risk-controlled'],['Macro reversal','Trend break during a regime transition.','Neutral to positive'],['Leverage stress','Position scaling with higher costs.','Stable within range']].map(x=>`<article class="metric-card"><div class="metric-label">${x[0]}</div><div class="metric-sub">${x[1]}</div><div class="metric-value" style="font-size:16px;color:#2bd49d">${x[2]}</div></article>`).join('');$('findings').innerHTML=['Gold remains a defensive anchor while Bitcoin captures the strongest upside participation.','NVIDIA offers growth exposure with materially higher volatility.','Return correlations remain moderate, supporting diversification.','The trend strategy is strongest when directional persistence is high.'].map(x=>`<div class="finding">${x}</div>`).join('');$('riskView').innerHTML=[['Risk budget','Moderate risk / high conviction'],['Macro regime','Bullish risk-on with controlled volatility'],['Action','Maintain trend exposure and rebalance on volatility expansion']].map(x=>`<div class="risk-item"><strong>${x[0]}</strong>${x[1]}</div>`).join('')}
async function init(){nav();showView('overview');$('overviewPeriod').addEventListener('change',loadOverview);$('assetSelect').addEventListener('change',()=>{loadExplorer();loadRegimes()});$('assetPeriod').addEventListener('change',loadExplorer);$('strategyRun').addEventListener('click',loadStrategy);$('backtestRun').addEventListener('click',()=>runBacktest());await loadOverview();await loadExplorer();await loadCorrelation();await loadStrategy();await runBacktest();await loadRegimes();loadStatic()}function start(){init().catch(error=>{$('sourceStatus').textContent='Connection error';$('lastUpdated').textContent=`Error: ${error.message}`;console.error(error)})}if(typeof Chart==='undefined'){const chartScript=document.createElement('script');chartScript.src='https://cdn.jsdelivr.net/npm/chart.js';chartScript.onload=start;chartScript.onerror=()=>{$('lastUpdated').textContent='Chart library unavailable'};document.head.appendChild(chartScript)}else{start()}
