const API='http://127.0.0.1:8000/api';const assets=[{key:'gold',label:'Gold',color:'#7f8cff'},{key:'bitcoin',label:'Bitcoin',color:'#ff5a3d'},{key:'nvidia',label:'NVIDIA',color:'#00d5a0'}];const views={overview:['◈','Overview','Market overview'],explorer:['▣','Asset Explorer','Technical intelligence'],correlation:['◫','Correlation Lab','Cross-asset dependency map'],strategy:['⚡','Strategy Lab','Quantitative Strategy Lab & Backtest Execution'],regimes:['△','Market Regimes','Macro climate decomposition'],adaptive:['◎','Adaptive Lab','Regime-aware allocation'],stress:['◇','Stress Lab','Edge-case resilience testing'],summary:['✦','Research Summary','Executive decision brief']};const charts={};const $=id=>document.getElementById(id);if(typeof Chart!=='undefined'){Chart.defaults.color='#8d95a5';Chart.defaults.font.family='IBM Plex Sans, Segoe UI, sans-serif'}

function nav(){const html=Object.entries(views).map(([key,v])=>`<button class="nav-button" data-view-button="${key}"><b>${v[0]}</b>${v[1]}</button>`).join('');$('desktopNav').innerHTML=html;$('mobileNav').innerHTML=html;document.querySelectorAll('[data-view-button]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.viewButton)));}
function showView(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.dataset.view===name));document.querySelectorAll('[data-view-button]').forEach(button=>button.classList.toggle('active',button.dataset.viewButton===name));$('sectionEyebrow').textContent=views[name][1];$('pageTitle').textContent=views[name][2];}
async function get(path){const response=await fetch(API+path);if(!response.ok)throw new Error(path);return response.json()}
function metric(label,value,sub=''){return `<article class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div>${sub?`<div class="metric-sub">${sub}</div>`:''}</article>`}
function pct(value,digits=2){return `${(Number(value||0)*100).toFixed(digits)}%`}function money(value){return `$${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:2})}`}
function normalize(series){const first=Number(series[0]?.close)||1;return series.map(row=>Number(row.close)/first*100)}
function destroy(name){if(charts[name])charts[name].destroy()}
function lineChart(name,id,labels,datasets,options={}){destroy(name);charts[name]=new Chart($(id),{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},animation:{duration:350},plugins:{legend:{labels:{color:'#cbd2de'}},tooltip:{backgroundColor:'#171b23',borderColor:'#343b49',borderWidth:1}},scales:{x:{grid:{color:'rgba(122,133,151,.12)'},ticks:{maxTicksLimit:8,maxRotation:0,color:'#8d95a5'}},y:{grid:{color:'rgba(122,133,151,.16)'},ticks:{color:'#8d95a5'}}},...options}})}
async function loadOverview(){
	const data=await get('/assets');
	const cards=data.assets||[];
	$('overviewCards').innerHTML=cards.map(item=>metric(item.label,money(item.summary.price),`Daily ${pct(item.summary.daily_change)} | Sharpe ${Number(item.summary.sharpe||0).toFixed(2)}`)).join('');
	const period=$('overviewPeriod').value;
	const payloads=await Promise.all(assets.map(asset=>get(`/assets/${asset.key}?period=${period}`)));
	const labels=payloads[0].series.map(row=>row.date);
	const datasets=payloads.map((payload,i)=>({label:assets[i].label,data:normalize(payload.series),borderColor:assets[i].color,pointRadius:0,borderWidth:2,tension:.12}));
	lineChart('performance','performanceChart',labels,datasets);
	$('sourceStatus').textContent=payloads.every(p=>p.live)?'Live sync online':'Fallback data online';
	$('lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString()}`;
}
async function loadExplorer(){const data=await get(`/assets/${$('assetSelect').value}?period=${$('assetPeriod').value}`);const s=data.series||[];const sum=data.summary||{};$('assetMetrics').innerHTML=[metric('Price',money(sum.price)),metric('Daily',pct(sum.daily_change)),metric('Sharpe',Number(sum.sharpe||0).toFixed(2)),metric('Max drawdown',pct(sum.max_drawdown))].join('');const last=s[s.length-1]||{};const signals=[['50 EMA',last.close>last.ema50?'Bullish':'Below average',last.close>last.ema50?78:35],['200 EMA',last.close>last.ema200?'Trend support':'Trend risk',last.close>last.ema200?72:30],['Volatility',`${pct(last.volatility)} annualized`,Math.min(95,Number(last.volatility||0)*140)],['Drawdown',pct(last.drawdown),Math.max(8,100+Number(last.drawdown||0)*180)]];$('signals').innerHTML=signals.map(x=>`<div class="signal"><div class="signal-top"><span>${x[0]}</span><span>${x[1]}</span></div><div class="signal-bar"><i style="width:${x[2]}%"></i></div></div>`).join('');lineChart('asset','assetChart',s.map(x=>x.date),[['Close','close','#e8ebf0'],['SMA50','sma50','#f5c451'],['EMA50','ema50','#7f8cff'],['EMA200','ema200','#00d5a0']].map(x=>({label:x[0],data:s.map(row=>row[x[1]]),borderColor:x[2],pointRadius:0,borderWidth:x[0]==='Close'?2:1.4,tension:.18})))}
async function loadCorrelation(){const data=await get('/correlation');$('correlationSource').textContent=data.source||'';const labels=data.labels||[];const matrix=data.matrix||[];Plotly.newPlot('correlationMatrix',[{z:matrix,x:labels,y:labels,type:'heatmap',zmin:-1,zmax:1,colorscale:[[0,'#063b73'],[.25,'#5ba5d8'],[.5,'#fff0e8'],[.75,'#f58f68'],[1,'#790021']],hovertemplate:'Ticker: %{y}<br>Ticker: %{x}<br>Correlation: %{z:.6f}<extra></extra>',text:matrix.map(row=>row.map(value=>Number(value).toFixed(6))),texttemplate:'%{text}',textfont:{color:'#142033',size:11},showscale:true,colorbar:{title:'Correlation',tickvals:[-1,-.5,0,.5,1],ticktext:['-1','-0.5','0','0.5','1'],titlefont:{color:'#e8ebf0'},tickfont:{color:'#e8ebf0'}}}],{paper_bgcolor:'#10131a',plot_bgcolor:'#10131a',font:{color:'#e8ebf0'},margin:{l:100,r:80,t:20,b:85},xaxis:{title:'Ticker',gridcolor:'#252b36'},yaxis:{title:'Ticker',autorange:'reversed',gridcolor:'#252b36'},hovermode:'closest'}, {responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']});}
function setMetrics(id,items){$(id).innerHTML=items.map(x=>metric(x[0],x[1],x[2]||'')).join('')}
async function runBacktest(asset=$('backtestAsset').value){const body={asset,initial_capital:Number($('capital').value)||10000,position_size:Number($('position').value)||1,transaction_cost:Number($('cost').value)||0};const response=await fetch(API+'/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();const m=data.metrics||{};setMetrics('backtestMetrics',[['Total return',pct(m.total_return)],['Sharpe',Number(m.sharpe||0).toFixed(2)],['Max drawdown',pct(m.max_drawdown)],['Final value',money(m.final_value)]]);lineChart('backtest','backtestChart',(data.curve||[]).map(x=>x.date),[{label:'Strategy',data:(data.curve||[]).map(x=>x.strategy),borderColor:'#00d5a0',pointRadius:0,borderWidth:2,tension:.2},{label:'Buy & Hold',data:(data.curve||[]).map(x=>x.benchmark),borderColor:'#f5c451',pointRadius:0,borderWidth:1.5,tension:.2}]) ;return m}
async function loadStrategy(){const body={asset:$('strategyAsset').value,initial_capital:Number($('capital').value)||140000,position_size:1,transaction_cost:(Number($('cost').value)||0)/100,strategy:$('strategySelect').value,fast_window:Number($('fastWindow').value),slow_window:Number($('slowWindow').value)};const response=await fetch(API+'/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();const m=data.metrics||{};$('strategySource').textContent=data.source||'';setMetrics('strategyMetrics',[['Strategy Return',pct(m.total_return)],['Benchmark Return',pct(m.benchmark_return)],['Sharpe Ratio',Number(m.sharpe||0).toFixed(2)],['Total Trades Executed',String(m.total_trades||0)]]);lineChart('strategy','strategyChart',(data.curve||[]).map(x=>x.date),[{label:'Strategy (EMA Trend)',data:(data.curve||[]).map(x=>x.strategy),borderColor:'#7f8cff',pointRadius:0,borderWidth:1.5,tension:.15},{label:'Buy & Hold Benchmark',data:(data.curve||[]).map(x=>x.benchmark),borderColor:'#ff5a3d',pointRadius:0,borderWidth:1.5,tension:.15}]);$('tradeLog').innerHTML=`<table class="trade-table"><thead><tr><th>Date</th><th>Action</th><th>Execution Price (₹)</th><th>Portfolio Valuation (₹)</th></tr></thead><tbody>${(data.trades||[]).slice(-20).reverse().map(row=>`<tr><td>${row.date}</td><td>${row.action}</td><td>${Number(row.execution_price).toLocaleString()}</td><td>${Number(row.portfolio_value).toLocaleString()}</td></tr>`).join('')}</tbody></table>`}
async function loadRegimes(){const asset=$('regimeAsset')?.value||$('assetSelect').value;const data=await get(`/regimes/${asset}`);const rows=data.regimes||[];const current=data.current||{};$('regimeSource').textContent=data.source||'';$('currentRegime').textContent=current.regime||'Unknown';$('currentRegimeMeta').textContent=`${current.trend||'Unknown'} trend · ${current.volatility_state||'Unknown'} · ${current.date||''}`;$('currentRegimeDot').style.background=current.color||'#93a4bc';$('regimeCards').innerHTML=rows.map(x=>metric(x.regime,`${x.days} days`,`${pct(x.return)} return | ${pct(x.volatility)} vol`)).join('');$('regimeTable').innerHTML=`<table class="trade-table regime-table"><thead><tr><th>Regime</th><th>Days</th><th>Return</th><th>Volatility</th></tr></thead><tbody>${rows.map(x=>`<tr><td><span class="regime-swatch" style="background:${x.color}"></span>${x.regime}</td><td>${x.days}</td><td>${pct(x.return)}</td><td>${pct(x.volatility)}</td></tr>`).join('')}</tbody></table>`;const timeline=data.timeline||[];if(typeof Plotly!=='undefined'){Plotly.newPlot('regimeTimeline',[{x:timeline.map(x=>x.date),y:timeline.map(x=>1),mode:'markers',type:'scatter',marker:{size:10,color:timeline.map(x=>x.color),symbol:'square'},customdata:timeline.map(x=>[x.regime,x.trend,x.volatility_state]),hovertemplate:'Date: %{x}<br>Regime: %{customdata[0]}<br>Trend: %{customdata[1]}<br>Volatility: %{customdata[2]}<extra></extra>',showlegend:false}],{paper_bgcolor:'#10131a',plot_bgcolor:'#10131a',margin:{l:25,r:20,t:20,b:45},xaxis:{gridcolor:'rgba(148,163,184,.15)',tickfont:{color:'#a8b0bf'},nticks:8},yaxis:{visible:false,fixedrange:true},hovermode:'closest'},{responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']})}destroy('regime');charts.regime=new Chart($('regimeChart'),{type:'bar',data:{labels:rows.map(x=>x.regime),datasets:[{label:'Regime return',data:rows.map(x=>Number(x.return)*100),backgroundColor:rows.map(x=>x.color),borderRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#a8b0bf'}},y:{grid:{color:'rgba(148,163,184,.14)'},ticks:{color:'#a8b0bf',callback:v=>`${v}%`}}}}})}
async function loadRegimePerformance(){const asset=$('regimeAsset').value;const regime=$('regimeScenario').value;const data=await get(`/regime-performance/${asset}?regime=${regime}`);$('regimeStrategyTable').innerHTML=`<div class="panel-heading"><div><span class="eyebrow">Selected macro regime</span><h2>${data.regime_label}</h2></div><span class="status">${data.source}</span></div><table class="trade-table regime-comparison-table"><thead><tr><th>Quantitative Strategy</th><th>Period Return (%)</th><th>Sharpe Ratio</th><th>Max Drawdown (%)</th><th>Trades</th></tr></thead><tbody>${(data.strategies||[]).map(row=>`<tr><td>${row.strategy}</td><td>${pct(row.period_return)}</td><td>${Number(row.sharpe||0).toFixed(2)}</td><td>${pct(row.max_drawdown)}</td><td>${row.trades}</td></tr>`).join('')}</tbody></table>`}
function loadStatic(){setMetrics('adaptiveCards',[['Adaptive score','81.4','Risk-adjusted allocation score'],['Suggested allocation','42 / 33 / 25','BTC / Gold / NVIDIA'],['Regime adjustment','Bullish tilt','Trend exposure maintained']]);destroy('adaptive');charts.adaptive=new Chart($('adaptiveChart'),{type:'bar',data:{labels:['Gold','Bitcoin','NVIDIA'],datasets:[{label:'Suggested weight',data:[33,42,25],backgroundColor:['#f5c451','#ff5a3d','#00d5a0']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});$('stressCards').innerHTML=[['Liquidity shock','Fast volatility spike with elevated drawdown risk.','Risk-controlled'],['Macro reversal','Trend break during a regime transition.','Neutral to positive'],['Leverage stress','Position scaling with higher costs.','Stable within range']].map(x=>`<article class="metric-card"><div class="metric-label">${x[0]}</div><div class="metric-sub">${x[1]}</div><div class="metric-value" style="font-size:16px;color:#2bd49d">${x[2]}</div></article>`).join('');$('findings').innerHTML=['Gold remains a defensive anchor while Bitcoin captures the strongest upside participation.','NVIDIA offers growth exposure with materially higher volatility.','Return correlations remain moderate, supporting diversification.','The trend strategy is strongest when directional persistence is high.'].map(x=>`<div class="finding">${x}</div>`).join('');$('riskView').innerHTML=[['Risk budget','Moderate risk / high conviction'],['Macro regime','Bullish risk-on with controlled volatility'],['Action','Maintain trend exposure and rebalance on volatility expansion']].map(x=>`<div class="risk-item"><strong>${x[0]}</strong>${x[1]}</div>`).join('')}
async function init(){nav();showView('overview');$('overviewPeriod').addEventListener('change',loadOverview);$('assetSelect').addEventListener('change',()=>{loadExplorer()});$('assetPeriod').addEventListener('change',loadExplorer);$('regimeAsset').addEventListener('change',()=>{loadRegimes();loadRegimePerformance()});$('regimeScenario').addEventListener('change',loadRegimePerformance);$('strategyRun').addEventListener('click',loadStrategy);$('fastWindow').addEventListener('input',event=>$('fastOutput').value=event.target.value);$('slowWindow').addEventListener('input',event=>$('slowOutput').value=event.target.value);$('cost').addEventListener('input',event=>$('costOutput').value=`${Number(event.target.value).toFixed(2)}%`);await loadOverview();await loadExplorer();await loadCorrelation();await loadStrategy();await loadRegimes();await loadRegimePerformance();loadStatic()}function start(){init().catch(error=>{$('sourceStatus').textContent='Connection error';$('lastUpdated').textContent=`Error: ${error.message}`;console.error(error)})}if(typeof Chart==='undefined'){const chartScript=document.createElement('script');chartScript.src='https://cdn.jsdelivr.net/npm/chart.js';chartScript.onload=start;chartScript.onerror=()=>{$('lastUpdated').textContent='Chart library unavailable'};document.head.appendChild(chartScript)}else{start()}
